### ISSUE TITLE
Add support for plugins: Phase I

### ISSUE THREAD

**Issue by bobbermac** [clojusc/dragon#2]
I'd like to write a dragon plugin that adds Flickr images to blog posts (of a given size, arrangement, and link back to Flickr). There's a ticket for this here:
 * https://github.com/forgotten-roads/blog/issues/82

In order to do this, though, I need to inject a task into the normal content-parsing workflow, before markdown is converted to HTML.

In order to *that*, I need Dragon to be event-driven (see #1). With that in place, adding plugin support should be pretty straight-forward.

Phase I Tasks (Milestone 0.5.0):

* [x] Examine the markdown-specific workflow
  * [x] identify any inconsistencies or redundancies therein
  * [x] generalize these for all types of content
  * [x] once #1 is complete, add any missing content-specific events
* [x] Identity a general way of handling content data - this will essentially become the "plugin framework"
  * [x] from data source through to final output form
  * [x] should be amenable to use with threading macros
  * [x] possibly take inspiration from Ring handlers
* [x] Identify all new default/general content events that should be published
  * identify ways in which "plugins" could publish events that other plugins could consume
  * maybe specify that each plugin should provide a before and after event for each action event?

Phase II Tasks:
 * See https://github.com/clojusc/dragon/issues/43

Phase III Tasks:
 * See https://github.com/clojusc/dragon/issues/44

**Comment by oubiwann** [comment]
Phase I has been completed.
