### ISSUE TITLE
Add support for plugins: Phase II

### ISSUE THREAD

**Issue by oubiwann** [clojusc/dragon#43]
I'd like to write a dragon plugin that adds Flickr images to blog posts (of a given size, arrangement, and link back to Flickr). There's a ticket for this here:
 * https://github.com/forgotten-roads/blog/issues/82

In order to do this, though, I need to inject a task into the normal content-parsing workflow, before markdown is converted to HTML.

In order to *that*, I need Dragon to be event-driven (see #1). With that in place, adding plugin support should be pretty straight-forward.

Phase I Tasks (Milestone 0.5.0):
 * See https://github.com/clojusc/dragon/issues/2

Phase II Tasks:

* [ ] Add a plugin component
  * [ ] should include a plugin registry at the very least
* [ ] Identify existing ad-hoc content parsing/munging/hacking rules
  * [ ] separate these from existing, critical, general workflow
  * [ ] add them as new "plugins" (i.e., use the new data workflow API)
* [ ] Implement an initial plugin (e.g., https://github.com/forgotten-roads/blog/issues/82)

Phase III Tasks:

 * See https://github.com/clojusc/dragon/issues/
