### ISSUE TITLE
Add support for plugins: Phase III

### ISSUE THREAD

**Issue by oubiwann** [clojusc/dragon#44]
I'd like to write a dragon plugin that adds Flickr images to blog posts (of a given size, arrangement, and link back to Flickr). There's a ticket for this here:
 * https://github.com/forgotten-roads/blog/issues/82

In order to do this, though, I need to inject a task into the normal content-parsing workflow, before markdown is converted to HTML.

In order to *that*, I need Dragon to be event-driven (see #1). With that in place, adding plugin support should be pretty straight-forward.

Phase I Tasks (Milestone 0.5.0):
 * See https://github.com/clojusc/dragon/issues/2

Phase II Tasks:
 * See https://github.com/clojusc/dragon/issues/43

Phase III Tasks:

* [ ] Identify other areas of Dragon that can be converted to using this new infrastructure
* [ ] Document how plugins need to be configured in order to 
  * [ ] define a specific function that gives all its subscribers
  * [ ] define and publish pre- and post- events for every function that will operate on dragon data (so that other plugins may determine if they need to go before or after another plugin
  * [ ] listen for the right events
  * [ ] take actions at the right times
  * [ ] publish their own events
  * [ ] suggest plugin code layout:
    * [ ] `name.plugin.main`?
    * [ ] `name.plugin.events`?
    * [ ] `name.plugin.subscribers`?
