### ISSUE TITLE
Add support for render-time plugins

### ISSUE THREAD

**Issue by oubiwann** [clojusc/dragon#64]
* [ ] Define a new multi-value header (e.g., `Plugins:`)
* [ ] Figure out a good way to:
    * [ ] associate a plugin value with code, html snippet resources, etc.
    * [ ] include these in the final rednered page output
* [ ] Plugins to support:
    * [ ] MathJax (see https://www.mathjax.org/#gettingstarted)
    * [ ] ToC for Post Series (e.g, use `Category:` header, sort by time, etc.)
    * [ ] Post-based ads
    * [ ] Front-page-based ads
    * [ ] Listing-page-based ads
